dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: my-test-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.18-SNAPSHOT
